lexica/lexica

- app/src/main/java/com/serwylo/lexica/game/Board.java
- app/src/main/java/com/serwylo/lexica/game/Game.java
- libraries/trie/src/main/java/net/healeys/trie/CompressedTrie.java
- libraries/trie/src/main/java/net/healeys/trie/Trie.java
- libraries/trie/src/test/java/com/serwylo/lexica/trie/tests/Utils.java
Less usage of abbreviated terms. Also formatted many of the
bit shifting operations to add more whitespace.
> Rename methods/variables in trie code to clarify behaviour.

- app/build.gradle
Fixes #21 
I've enabled for debug builds as well as release builds. This is so that during testing of debug builds, it should be easier to notice bugs that would affect release builds. If the extra build time becomes a problem for debug builds, then this can be revisited.
> Enable proguard to reduce apk size

- README.md
Update both the F-Droid and Google Play badges were out of date, this fixes that to use the newly published F-Droid artwork and the more recent Google Play badge. I've also updated https://lexica.github.io/lexica separately to this MR.
Fixes #25.
> Updated "Get it on..." logos to new artwork.

- app/src/main/java/com/serwylo/lexica/Lexica.java
- app/src/main/java/com/serwylo/lexica/LexicaConfig.java
- app/src/main/java/com/serwylo/lexica/ScoreActivity.java
- app/src/main/java/com/serwylo/lexica/view/LexicaLogo.java
- app/src/main/res/layout-land/splash.xml
- app/src/main/res/layout-port/splash.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
* A high score may be saved for each unique combination of dictionary, board size, time limit, and scoring type
* The current combination's high score displays on the splash screen
* High scores can be reset in the preferences menu with a prompt
* Ensure that splash tiles are the same size in portrait and landscape modes
* Put splash buttons in one row in landscape mode.
> Add high score tracking

- app/src/main/java/com/serwylo/lexica/game/Game.java
The comment "Every word goes through the filter ..." was incorrect.
Every *solution* goes through the filter, so words with multiple
solutions were being counted too many times.
> Fix word length breakdown counts

- gradle/wrapper/gradle-wrapper.properties
Hello @pserwylo 
Grade version is updated to the latest version, because the version 3.3 can not determine the java version. The error message is the following:
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine java version from '10.0.1'.
> Updated grade to version 4.8.1

- .travis.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/serwylo/lexica/game/Game.java
- app/src/main/java/com/serwylo/lexica/view/LexicaView.java
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- app/src/test/java/com/serwylo/lexica/FullUsGbTrieTest.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Drop the build tool changes introduced while adding "Tile weights". I'd prefer to have this in a separate release when there is a reason to do so, otherwise it will increase the testing burden prior to release.. Also rename tile weights to "hint mode".
> Tweak tile weights

- app/src/main/java/com/serwylo/lexica/LexicaConfig.java
- app/src/main/java/com/serwylo/lexica/Util.java
- app/src/main/java/com/serwylo/lexica/game/Game.java
- app/src/main/res/xml/preferences.xml
Fixes #138 
The main issue is that if the preferences screen is ever opened, the language is written to the SharedPreferences and thus locked and won't update automatically based on device language changes anymore. Because the user never chose a language, I consider this a bug, but most users will probably never change their device language. It just means that existing users will have to manually change their language if they ever opened the preferences screen before.
> Default to Android system language dictionary

- app/src/main/res/values/colours.xml
- app/src/main/res/values/styles.xml
Fixes #149. Uses colours from colour brewer (colour brewer 2 swatch from #149).
**Fixed:**
**Broken:**
> Use appropriate hint mode colours for dark theme.

- app/src/main/java/com/serwylo/lexica/view/LexicaView.java
Fixes #150 
Show the points for selected word, but also use a fainter colour for previously selected words.
Unsure if I've done the right thing by RTL languages or not, I use "+1 WORD" for RTL, and "WORD +1" for LTR.
> Show points for selected word

- app/src/main/AndroidManifest.xml
- metadata/android/en-US/changelogs/10100.txt
* End game when all words found (thanks adam-poteralowicz)
* Fixed dark theme hint mode colours
The first one is what bumps it to a minor release. If it was just the fix to dark theme, I'd have gone v1.0.1.
> Bump for release v1.1.0

- .github/FUNDING.yml
Experimenting with this. In the future it would be nice to move towards other, more free and open platforms such as OpenCollective or LiberaPay, but for now this was quite straightforward to setup.
> Enable sponsorship via GitHub sponsors

- libraries/trie/src/main/java/com/serwylo/lexica/lang/Russian.java
In the future, perhaps this can be the default instead of DuckDuckGo, because it
is by the Wikimedia Foundation rather than a commercial provider.
Fixes #103.
> Use wiktionary to define Russian words

- app/src/main/java/com/serwylo/lexica/SettingsFragment.java
Fixes #147. Prior to this, one could only click 'Ok' or click behind the modal dialog 9counterintuitively).
> Allow 'cancel' option when resetting high scores.

- app/src/main/java/com/serwylo/lexica/GameActivity.java
Stop after 5 attempts though, because for some languages and board sizes (e.g. large Japanese boards)
it will never get many words, so just cut our losses.
Also don't try forever for performance reasons. This is a naive approach that runs on the UI thread
with no loading feedback to the user, so lets try to keep it lean on slower devices.
In the future, this would be better refactored into a different thread,
with a loading screen shown to the user.
Fixes #124.
> Try to ensure boards with at least 45 words.

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/10200.txt
Phew, that was a fun few days of development. Thanks to all those in the community posting issues and proposing improvements.
Here are the release notes:
> News:
>  * Support Lexica development via GitHub Sponsors :)
> 
> Features:
>  * Sort list of words at the end of the game (thanks gsheridansmith)
>  * New Russian dictionary (thanks ildar)
>  * High contrast theme
>  * Russian words defined using wiktionary instead of DDG
>  * Prefer game boards with at least 45 words
> 
> Bugfixes:
>  * Fix misaligned buttons in certain languages
>  * Add missing "cancel" option when resetting high scores
> 
> Please provide any feedback or report any issues on the issue tracker at https://github.com/lexica/lexica/issues.
>>>
> Bump for release v1.2.0

- app/src/main/java/com/serwylo/lexica/activities/score/WordDefiner.java
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- app/src/test/java/com/serwylo/lexica/FindLanguageMatchingLocale.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Catalan.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/DeGerman.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Dutch.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/English.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/French.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Hungarian.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Italian.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Japanese.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Language.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Persian.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Polish.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/PortugueseBR.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Russian.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Spanish.java
- libraries/trie/src/main/java/com/serwylo/lexica/lang/Ukrainian.java
Polish doesn't use it, as Polish has a definition service that comes from the wordlist provider.
Preferable to DuckDuckGo because it is more open, and supports multiple languages.
Hopefully there is a nice offshoot that if someone tries to define a word that
doesn't exist in Wiktionary yet (e.g. Ukranian only has on the order of 10,000 words)
then players could add a definition.
Fixes #186 (doesn't use WordReference, but does use a Spanish specific version of Wiktionary).
> Default to Wiktionary when defining words for all languages

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/10300.txt
Wiktionary for definitions, instead of DuckDuckGo.
> Bump for release v1.3.0

- .github/FUNDING.yml
- README.md
Still a bit of an experiment to allow people who wish to donate to do so.
First attempt was GitHub sponsors, but that doesn't integrate as well with F-Droid.
Also update the readme with more details about the difference from the original lexica (a lot has changed!)
> Add liberapay donation option.

- build.gradle
- libraries/language-analysis/build.gradle
This was broken with an upgrade to the gradle files, whereby the 'compilation' dependencies
were replaced with 'implementation'. There are plenty of workarounds online, but the best
approach seemed to be to use a 3rd party plugin which does this for us. That should future
proof it from futher changes in the future.
> Fix broken "analyseLanguage" tasks used for generating letter probability distributions.

- app/src/main/res/xml/preferences.xml
Android reserves some space next to a preference to let developers put an icon there.
As there aren't any icons, I added android:iconSpaceReserved="false" to all the preferences in order to "remove" this useless blank space.
> Made the preferences not retain the margin reserved to icons

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/20000.txt
First alpha release, so will tag manually in F-Droid until
fdroidserver supports regex'es for non-suggested versions.
> Bump for release 2.0.0-alpha1.

- app/build.gradle
- app/src/main/java/com/serwylo/lexica/game/Game.java
Correctly process min-world-length property.
Was accidentally overwriting it based on the old board-size logic immediately after reading it from the game mode.
> Fix min world length

- app/build.gradle
- app/src/main/java/com/serwylo/lexica/ChooseLexiconActivity.kt
- app/src/main/java/com/serwylo/lexica/MainMenuActivity.java
- app/src/main/java/com/serwylo/lexica/Util.java
- app/src/main/java/com/serwylo/lexica/game/Game.java
- fastlane/metadata/android/en-US/changelogs/20003.txt
- libraries/trie/src/test/java/com/serwylo/lexica/lang/LanguageTest.kt
Fix issues where devices with French and German locales will crash when trying to find a sensible default language to use for the game. 
This is due to a broken assumption that the system locale is identical to the "name" of the language in Lexica. This assumption was broken for fr + de, because there we end up with a "locale" of fr_FR or de_DE, but a "name" of fr or de. 
Changing the assumption means we really need to ensure that the `Language.allLanguages` map is correct whereby the key of the map is the same as the corresponding values "name". Therefore added a test case to assert this.
Fixes #221
> Fix alpha npe on startup

- app/src/main/java/com/serwylo/lexica/game/Game.java
Based on https://stackoverflow.com/a/47123976/2391921 and other
such answers saying that the volume must be betwen 0.0 and 1.0.
In practice, the volume was a number such as 11 when testing here.
Still not sure why this broke it, but seems to work now.
> Allow consecutive sounds to play.

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/20010.txt
Multiplayer improvement:
* Show how many words in the board prior to inviting others or joining a game.
* If you prefer more or less words for your multiplayer game, you can now refresh the board prior to playing.
Bug fix:
* Consecutive sound effects now play as expected (One of the oldest reported bugs, from 2017, thanks for the report @PakoPakoJr!)
Enjoy Lexica? Support further development via Liberapay or GitHub Sponsors.
> Bump for release - v2.3.0

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/20016.txt
Additional Spanish dictionary with Ñ but not other diacritics. Thanks @jgmy, I'll merge this and then tag a new release. F-Droid is [currently in the process of building v2.5.2](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500). Once that is done then it will pick up this and build then release it.
> Bump for release v2.6.0 - Additional Spanish dictionary

- app/build.gradle
- app/src/main/java/com/serwylo/lexica/share/SharedGameData.kt
- app/src/main/java/com/serwylo/lexica/share/SharedGameDataHumanReadable.kt
- app/src/test/java/android/util/Base64.java
- app/src/test/java/com/serwylo/lexica/ShareQrTest.kt
As described in #256 games with "Qu" (or other multi character cells) cannot be successfully shared in multiplayer mode.
The problem is that there is no separator between the cells so the assumption is that there is a single character per cell. This change creates a separator (an underscore) so that we don't have to rely on the assumption.
The drawback is that this will break sharing with older clients (sharing from an older client is supported albeit no attempt is made to handle the "Qu" case so that will still break). Because this introduces an incompatible change I've bumped the versionCode.
A related change will be needed for the web page on https://lexica.github.io/
> Fix multiplayer games with "Qu"

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/30000.txt
Requires a corresponding fix to the website to be released prior to merging and releasing this.
> Bump for release v3.0.0 - Fix multiplayer boards with Qu and Base64 encode.

- assets/dictionaries/dictionary.nl.txt
Cautiously improve Dutch word list, making it more conforming to the Scrabble word list ([SWL](https://www.ntsv.eu/index.php/taal-2020/woordenlijsten2020/swl-2017bis)), [OpenTaal](https://www.opentaal.org/) list, and [Wiktionary](https://nl.wiktionary.org/wiki/WikiWoordenboek:Hoofdpagina).
Remove words that are neither in the Scrabble word list (SWL), OpenTaal list, and Wiktionary. Many of these are loan-words or partial words that are only valid in combination with other words. E.g. "oetan" is only valid in "orang-oetan".
Add words that are in all three of Wiktionary, Scrabble word list (SWL) and OpenTaal list, excluding capitalized words.
> Dutch dict improvements

- assets/dictionaries/dictionary.en_GB.txt
Remove words where the word itself or its base is not in Collins, NASPA,
Tournament or Wiktionary.
Related to #313.
> Remove words that are in none of the wordlists

- app/src/main/AndroidManifest.xml
Replaced android:path with android:pathPrefix to handle android links.
> Fix for multiplayer Android 6.0 link #318

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/30008.txt
Improvements (thanks to Sjord):
* English (GB) wordlist: Remove words that are not present in Collins, NASPA, Tournament, or Wiktionary.
* Dutch dictionary: Better letter distributions for more fun games.
Bug fix (thanks to OpenWarp):
* Multiplayer correctly opens on Android 6.0.
Please provide feedback/report issues at https://github.com/lexica/lexica/issues.
> Bump for release v3.6.1 - Misc improvements

- .github/workflows/api.yml
This is required after bumping the gradle version.
I didn't pick it up on the original change because that doesn't run the API CI until after merging to master (due to it deploying artifacts).
> Use JDK 11 to build API.

- app/src/main/java/com/serwylo/lexica/game/Game.java
Fixes #348
However, the fix doesn't apply to the cases of 99,999,999 minutes and more - because 99,999,999 * 60 seconds = 5,999,999,940 seconds, which exceeds Java Integer max value, and `timeLimitSeconds` is Int. 
@pserwylo: perhaps it makes sense to introduce a sensible fixed upper time limit like Integer max value?
> Fix overflowing time limit

- libraries/liblexica/src/main/java/com/serwylo/lexica/game/CharProbGenerator.java
In theory, this will have some sort of impact on the number of words available on larger boards (beyond 4x4), but with a cursory test of a few board generations in English (UK), it didn't have a large impact.
Even if it does have a large impact, it is still better to do this right and address consequences as they come, rather than having a strange corner in the bottom right with less common letters.
> Ensure all letters are shuffled correctly (not just the first 15).

- app/src/main/java/com/serwylo/lexica/activities/score/ScoreCalculator.kt
There was a performance optimisation to not calculate the word score for found words twice. It did this by calculating the current score, then when calculating the max score, only do so for the words which have not yet been scored.
To make it clearer what is going on, it now just re-counts if neccesary. It doesn't seem like this performance hit is worth the chance of (well, the actual) bugs.
Fixes #315.
> Correctly show max score when viewing in-game found words.

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/30015.txt
Last attempt didn't increase version number, so F-Droid (correctly) didn't publish a new version when we tagged v3.11.0. Will remove v3.11.0 tag and recreate it.
> Actually bump for release v3.11.0.

- app/src/main/java/com/serwylo/lexica/NewGameModeActivity.kt
- app/src/main/res/values/strings.xml
Fixes #377 - the crashes should occur no more.
As part of this fix, I've incorporated the logic that @pserwylo hinted at in a comment on my previous fix (#351) - introducing a sensible time limit in days rather than millions of seconds. I've however arbitrarily chosen 30 days rather than 20 days - this is easily changeable. Also, in case the time limit exceeds that threshold / is zero / is blank, a suitable Snackbar message is shown.  One of them is visible in the example screenshot below:
> Handle time limit related crashes
