CHANGELOG.md, app/src/main/AndroidManifest.xml
Release which includes @residuum's German translations.
=> Bump for release v0.9.3

README.md
Got an account on https://hosted.weblate.org, so want to advertise that this is the preferred way to submit translations.
=> Added Weblate translation instructions

app/src/main/java/com/serwylo/lexica/ScoreActivity.java, app/src/main/res/values/strings.xml
=> Add percentage after total score.

README.md
Also fix some references to Lexic while I'm here.
=> Update "Get it on F-Droid" button image.

README.md
Finally added the app to Google Play, may as well link to it in the README.
=> Add "Get it on Google Play" badge after uploading to the Play Store.

app/src/main/res/values-ja/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, pull-trans.sh
The way Weblate works is to maintain a git repository which has this repository as a remote. Translations in Weblate includes commits on top of master for new translations. This script is adapted almost verbatim from that used by the F-Droid project. I'll create a wiki article explaining how to use the script to pull translations and prepare a MR in the future.
=> Script for pulling scripts from Weblate

CHANGELOG.md, app/src/main/AndroidManifest.xml
Japanese translations is good enough for me to bump this version number. Also added percentage of score/words to the final screen.
=> Bump for release v0.9.4

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa/strings.xml
=> Release v0.9.5

build.gradle
=> Fix typo in build file comment

app/src/main/res/values-nl/strings.xml
Translators:
Added translation using Weblate (Dutch) by Heimen Stoffels
=> Pull translation updates from Weblate

app/src/main/java/com/serwylo/lexica/ScoreActivity.java, app/src/main/java/com/serwylo/lexica/game/Game.java, app/src/main/java/com/serwylo/lexica/view/BoardView.java, app/src/main/java/com/serwylo/lexica/view/LexicaLogo.java, app/src/main/java/com/serwylo/lexica/view/LexicaView.java, app/src/test/java/com/serwylo/lexica/FullUsUkTrieTest.java, app/src/test/java/com/serwylo/lexica/TransitionMapTest.java, libraries/trie/src/main/java/net/healeys/trie/StringTrie.java, libraries/trie/src/main/java/net/healeys/trie/Trie.java, libraries/trie/src/test/java/com/serwylo/lexica/trie/tests/TrieTest.java
* Use accurate vertical centering algorithm for letters
* Consider paddingSize in BoardView to avoid the board getting cut off at the top
* Swap the timer and word count positions (in preparation for a more detailed scoring)
* Add score to missed words list
* Improve display of score in found word list
* Alphabetize missed word list
=> Clean up and/or improve some parts of the display

app/src/main/java/com/serwylo/lexica/GameSaver.java, app/src/main/java/com/serwylo/lexica/GameSaverPersistent.java, app/src/main/java/com/serwylo/lexica/GameSaverTransient.java, app/src/main/java/com/serwylo/lexica/ScoreActivity.java, app/src/main/java/com/serwylo/lexica/game/Game.java, app/src/main/java/com/serwylo/lexica/view/BoardView.java, app/src/main/java/com/serwylo/lexica/view/LexicaView.java, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
* Preference added to choose scoring type
* Enabling letter points based scoring also enables the display of letter points on the letters in the game and score views
* Timer/Score view updated to show current score
* Word list during game updated to show word scores
* Cleanup of the score and word list drawing code to properly reflect that the y-coordinate provided to drawText is the baseline of the text, not the top.
=> Add alternative scoring option

app/src/main/java/com/serwylo/lexica/game/Game.java, app/src/main/java/com/serwylo/lexica/view/LexicaView.java, app/src/main/res/values/sizes.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
NOTE: This pull request is dependent on PR42. It should be rebased before merging.
EDIT: rebase complete.
=> Add option to show word counts by length

app/src/main/java/com/serwylo/lexica/game/Game.java, app/src/main/java/com/serwylo/lexica/view/LexicaView.java
Last pull request from me. Just a minor display thing.
=> Don't show points next to already found words

app/src/main/java/com/serwylo/lexica/ScoreActivity.java, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Okay, so I was wrong - apparently I have a couple more pull requests left in me....
This one is in support of issue #11.
=> Add support for choosing a definition provider

app/src/main/res/values-bg/strings.xml
Hi! I want to translate and help with development. Currently I learn android via Udacity with Google Scholarship and I want to work on Open Source project like this.
=> Creating Initial Strings for Bulgarian Language

app/src/main/java/com/serwylo/lexica/ScoreActivity.java, app/src/main/res/values/donottranslate.xml, app/src/main/res/xml/preferences.xml
=> Switch default search provider to DuckDuckGo

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-th/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Pulled translations from Weblate. Then replaced "Google" with "DuckDuckGo" using `sed`.
=> Update translations with DDG instead of Google

app/src/main/res/values-de/strings.xml, app/src/main/res/values-fa/strings.xml, pull-trans.sh
Due to my silliness when I manually used sed to update translations, but
neglected to tell weblate that I had done so, there were some conflicts.
=> Pull translations (and fix weirdness due to manual translation changes).

app/build.gradle, app/src/main/AndroidManifest.xml
=> Hotfix 0.11.1

app/build.gradle, app/src/androidTest/java/com/serwylo/lexica/GenerateLanguageBoards.java, app/src/main/java/com/serwylo/lexica/ScoreActivity.java, app/src/main/java/com/serwylo/lexica/Synchronizer.java, app/src/main/java/com/serwylo/lexica/game/Game.java, app/src/main/java/com/serwylo/lexica/view/BoardView.java, app/src/main/java/com/serwylo/lexica/view/LexicaView.java, build.gradle, libraries/liblexica/src/main/java/com/serwylo/lexica/game/CharProbGenerator.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/Catalan.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/DeGerman.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/Dutch.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/English.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/French.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/Italian.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/Language.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/Persian.java, libraries/trie/src/main/java/com/serwylo/lexica/lang/Spanish.java, libraries/trie/src/main/java/net/healeys/trie/StringTrie.java
The actual point values are not perfect, but they at least approximate Scrabble scoring. Fixes #76.
=> Fix letter points for all languages  

app/src/main/AndroidManifest.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nl/strings.xml, metadata/android/en-US/changelogs/1104.txt
Added Japanese dictionary (thanks wichmann)
Russian translation (thanks HenriDellal)
=> Bump for release v0.11.4

app/src/main/AndroidManifest.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, metadata/android/en-US/changelogs/1105.txt
Hungarian dictionary and new/updated translations.
=> Bump for release v0.11.5

.travis.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/serwylo/lexica/ScoreActivity.java, app/src/main/java/com/serwylo/lexica/game/Game.java, app/src/main/java/com/serwylo/lexica/view/LexicaView.java, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/com/serwylo/lexica/BoardTransitionTest.java, app/src/test/java/com/serwylo/lexica/FullUsGbTrieTest.java, app/src/test/java/com/serwylo/lexica/TransitionMapTest.java, build.gradle, gradle/wrapper/gradle-wrapper.properties, libraries/liblexica/src/main/java/com/serwylo/lexica/game/Board.java, libraries/trie/src/main/java/net/healeys/trie/StringTrie.java, libraries/trie/src/main/java/net/healeys/trie/Trie.java, libraries/trie/src/test/java/com/serwylo/lexica/trie/tests/TrieTest.java
Adds display of tile weights, i.e. how many words can be spelled with that tile. Includes options for displaying as either a number, color, or both.
Adds some fixes for building that Android Studio complained about. I was not able to get just straight `gradle` working, but if those fixes cause any issues with `gradle` I can remove.
The weight color scheme is currently hard-coded, not sure how to handle that better atm.
=> Add display of tile weights

app/src/main/AndroidManifest.xml, metadata/android/en-US/changelogs/1200.txt
Ready to release with the new "Hint mode" added, and a Ukrainian dictionary. Will probably wait a few days as we already have translations around this hint mode for Japanese and Hungarian, so after another week there may be more (thanks translators!!!).
=> Bump for release 0.12.0

app/src/main/java/com/serwylo/lexica/activities/score/MissedWordsViewBinder.java, app/src/main/java/com/serwylo/lexica/activities/score/ScoreTabViewHolder.java, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
I've never done any android development before and I'm not sure what I'm supposed to about the translations, but this should fix #101 
Happy to try and add anything extra that's needed
=> WIP: Implement sorting modes for "missed words" end game screen #101

assets/dictionaries/README.md, assets/dictionaries/dictionary.ru.LICENSE
Also add instructions for new dictionaries to include attribution. Attribution for ru dict as per #161.
=> Attribute ru dictionary

app/build.gradle, app/src/main/java/com/serwylo/lexica/GameActivity.java, fastlane/metadata/android/en-US/changelogs/20001.txt
Fixes #211. See comment https://github.com/lexica/lexica/issues/211#issuecomment-742093304 for detailed description.
=> Fix crash preventing any games in 2.0.0-alpha1

app/build.gradle
Accidentally added a bump alpha3 again in previous fix branch, but should have been alpha4.
=> Bump for release v2.0.0-alpha4.

app/build.gradle, app/src/main/java/com/serwylo/lexica/ChooseGameModeActivity.kt, app/src/main/java/com/serwylo/lexica/GameActivity.java, app/src/main/java/com/serwylo/lexica/MainMenuActivity.java, app/src/main/java/com/serwylo/lexica/db/GameModeDao.kt, app/src/main/java/com/serwylo/lexica/db/GameModeRepository.kt, app/src/main/java/com/serwylo/lexica/db/ResultDao.kt, app/src/main/java/com/serwylo/lexica/db/SelectedWordDao.kt, app/src/main/java/com/serwylo/lexica/db/migration/MigrateHighScoresFromPreferences.kt, app/src/main/res/values/strings.xml, fastlane/metadata/android/en-US/changelogs/20004.txt
Fixes #219 and Fixes #224.
Only implemented the straightforward "Long press to delete" discussed in #219 (not some of the more useful user experiences). Open to PRs with other alternatives. Also a little bit weird in some themes such as high contrast, but still works.
=> Delete game modes

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/serwylo/lexica/GameActivity.java, app/src/main/java/com/serwylo/lexica/GameSaverPersistent.java, app/src/main/java/com/serwylo/lexica/MainMenuActivity.java, app/src/main/java/com/serwylo/lexica/SettingsActivity.java, app/src/main/java/com/serwylo/lexica/SettingsFragment.java, app/src/main/java/com/serwylo/lexica/activities/FoundWordsActivity.kt, app/src/main/java/com/serwylo/lexica/activities/HighScoresActivity.kt, app/src/main/java/com/serwylo/lexica/db/Database.java, app/src/main/java/com/serwylo/lexica/db/GameModeRepository.kt, app/src/main/java/com/serwylo/lexica/db/ResultDao.kt, app/src/main/java/com/serwylo/lexica/db/ResultRepository.kt, app/src/main/java/com/serwylo/lexica/db/SelectedWord.kt, app/src/main/java/com/serwylo/lexica/db/SelectedWordDao.kt, app/src/main/java/com/serwylo/lexica/db/SelectedWordRepository.kt, app/src/main/java/com/serwylo/lexica/db/migration/MigrateHighScoresFromPreferences.kt, app/src/main/java/com/serwylo/lexica/db/migration/Migration_1_2_RecordWhetherSelectedWordsAreWords.kt, app/src/main/java/com/serwylo/lexica/game/Game.java, app/src/main/java/com/serwylo/lexica/view/CustomTextArrayAdapter.kt, app/src/main/res/drawable/ic_found_words.xml, app/src/main/res/layout/found_word.xml, app/src/main/res/layout/found_words.xml, app/src/main/res/layout/high_score_list_item.xml, app/src/main/res/layout/high_scores.xml, app/src/main/res/layout/splash.xml, app/src/main/res/menu/high_scores_menu.xml, app/src/main/res/values/strings.xml, build.gradle
Allow high scores to be viewed by touching the high score on the home page. Shows high scores for any given combination of Lexicon + Game Mode. Once viewing a high score, you can view a list of found words by tapping the menu icon. These found words are per-language at this point in time (the database structure is such that we could change this to show per-game-mode words as well).
Closes #228.
=> View high scores and found words

app/src/main/java/com/serwylo/lexica/activities/MultiplayerLobbyActivity.kt, app/src/main/java/com/serwylo/lexica/activities/NewMultiplayerActivity.kt, app/src/main/res/layout/multiplayer_lobby.xml, app/src/main/res/layout/new_multiplayer.xml, app/src/main/res/values/strings.xml
Based on feedback from @frief here: https://github.com/lexica/lexica/issues/102#issuecomment-830331141
=> Show how many words in multiplayer befroe inviting.

app/build.gradle, app/src/main/java/com/serwylo/lexica/Changelog.kt, app/src/main/res/values/strings.xml, fastlane/metadata/android/en-US/changelogs/30005.txt
@MattRCole - sorry I didn't do this earlier, but bumping a release with your work in it now. Should take a few days for F-Droid to build and release. Hope you don't mind me crediting you in the changelog when it first opens:
=> Bump for release v3.4.0 - Web lexica link

app/src/main/java/com/serwylo/lexica/activities/score/FoundWordsViewBinder.java, app/src/main/java/com/serwylo/lexica/activities/score/ScoreWordsViewBinder.java
Also change font style and colour to match the in game word list.
Fixes #306.
=> Hide scores + define button for non-words on score screen.

app/src/main/java/com/serwylo/lexica/view/GameDetailsView.kt
=> Fix crash when trying to choose game mode on Android 4.4

app/src/main/java/com/serwylo/lexica/NewGameModeActivity.kt
Fixes #347 by preventing to save the new game mode when set time limit is 0.
=> Prevent from adding new game mode with time limit of zero

libraries/trie/src/main/java/com/serwylo/lexica/lang/BretonNoDiacritics.java
See https://github.com/lexica/lexica/pull/324/#issuecomment-1705586976
=> Make "C'h" trigram fit in the game cells by using a lowercase h

app/src/main/res/raw/letters_de_de_no_diacritics.txt, show-chars-in-dict.sh
Fixes #323.
Kind of arbitrary the new probabilities, but they are all arbitrary to start with. Generated these new probabilities by glancing at the frequency of each letter in the dictionary.
=> Increase probability of letter N in de_de_no_diacritics.

app/src/main/java/com/serwylo/lexica/view/LexicaView.java, app/src/main/res/layout/game_details.xml, app/src/main/res/layout/new_game_mode.xml, app/src/main/res/layout/new_multiplayer.xml
Update the game mode screen and multiplayer lobby to be responsive. Also a hack fix for the game screen on particularly small screens. Fixes #358.
=> Small screen support

app/src/main/java/com/serwylo/lexica/view/LexicaView.java
Previously drew based on their bounds, which meant that those with a 'Q' in them (and perhaps others) were drawn misaligned.
Fixes #194
=> Correctly draw words based on their baseline.
